version: '3.8'

services:
  app:
    image: postgres:16.2-alpine3.19
    container_name: app-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgres

    depends_on:
      - redis
      - celery_worker

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  redis:
    image: redis:7.2.4
    container_name: e-factory-redis
    command: redis-server
    ports:
      - 6379:6379

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - .:/server
    command: celery -A config worker -l info
    depends_on:
      - redis
volumes:
  postgres_data:
