# Generated by Django 4.2.16 on 2024-09-27 15:02

import os

import django.db.models.deletion
from django.db import migrations, models


def load_sql_script(apps, schema_editor):
    if os.getenv("DJANGO_ENV") == "production":
        path = "path/to/your/prod_script.sql"
    elif os.getenv("DJANGO_ENV") == "test":
        path = "path/to/your/test_script.sql"
    else:
        path = "scripts/dev_script.sql"
    with open(path, "r") as sql_file:
        sql_content = sql_file.read()
    schema_editor.execute(sql_content)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.question"
                    ),
                ),
            ],
        ),
        migrations.RunPython(load_sql_script),
    ]
