# Generated by Django 4.2.16 on 2024-10-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
