# Generated by Django 4.2.16 on 2024-10-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clientuser_userrefreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
